Send email on rent creation
wolox-training/megl-rails pull request #12
Opened 2019-04-01 19:15 UTC by marcegl91

### Summary

- Send email on rent creation.

### Trello Card

https://trello.com/c/Q2hlTy7r/10-mandar-email-al-usuario-cuando-se-crea-un-rent

2019-04-02 12:59 UTC, facucompe requested changes

2019-04-02 12:59 UTC, facucompe commented on wbooks-api/app/controllers/api/v1/rents_controller.rb
> +          RentCreationEmailWorker.perform_async(current_user.id, rent.id)
There is no need to create a worker to send the email. Look this [https://gist.github.com/maxivak/690e6c353f65a86a4af9](gist)

2019-04-05 13:27 UTC, facucompe approved these changes

2019-04-08 15:03 UTC, floresv approved these changes
LGTM

2019-04-08 15:40 UTC, merged