Pundit impl
wolox-training/megl-rails pull request #14
Opened 2019-04-03 19:08 UTC by marcegl91

### Summary

- Authorization of Rent resources with Pundit

### Trello Card

https://trello.com/c/UQXauDjk/11-instalar-y-configurar-pundit

2019-04-05 13:22 UTC, facucompe submitted a review, later dismissed

2019-04-08 18:05 UTC, floresv commented on wbooks-api/app/policies/rent_policy.rb
> +  class Scope < Scope
mmm.. I didn't see the policy methods like index and show of Rent. :thinking:

2019-04-08 18:06 UTC, floresv requested changes
Failure test? :sweat_smile:

2019-04-09 13:33 UTC, floresv approved these changes
LGTM

2019-04-09 13:50 UTC, facucompe approved these changes

2019-04-09 13:53 UTC, merged