Add test for OpenLibrary search method
wolox-training/megl-rails pull request #19
Opened 2019-04-04 19:01 UTC by marcegl91

### Summary

- Add tests for OpenLibrary search method with WebMock

### Trello Card

https://trello.com/c/S3MDg5ty/38-crear-tests-para-el-servicio-de-openlibrary

2019-04-10 14:21 UTC, facucompe requested changes

2019-04-10 14:21 UTC, facucompe commented on wbooks-api/spec/support/mocks_and_stubs/open_library_request_invalid.rb
> +  def self.call
I would send the isbn code as a parameter here

2019-04-10 14:21 UTC, facucompe commented on wbooks-api/spec/support/mocks_and_stubs/open_library_request_success.rb
> +  def self.call
same here

2019-04-10 14:21 UTC, facucompe commented on wbooks-api/spec/support/mocks_and_stubs/open_library_request_success.rb
> +module OpenLibraryRequestSuccess
I don't know if I would create another module for success response. You don't have to repeat yourself in the URL method for example.

2019-04-10 21:50 UTC, facucompe commented on wbooks-api/spec/services/open_library_service_spec.rb
> +require 'support/mocks_and_stubs/open_library_request'
I think that if you add `Dir[Rails.root.join('spec/support/**/*.rb')].each { |f| require f }
` this won't be needed in every file

2019-04-11 14:22 UTC, facucompe approved these changes

2019-04-11 14:28 UTC, floresv approved these changes
Good job!
![](https://media.giphy.com/media/nNxT5qXR02FOM/giphy.gif)

2019-04-11 14:33 UTC, merged