Add rubocop configuration
wolox-training/megl-rails pull request #2
Opened 2019-03-26 15:24 UTC by marcegl91

### Summary

- Implemented rubocop configuration.

### Trello Card

https://trello.com/c/0NWe4LI3/8-configurar-rubocop

2019-03-26 15:30 UTC, floresv submitted a review, later dismissed
LGTM

2019-03-26 19:37 UTC, facucompe requested changes

2019-03-26 19:37 UTC, facucompe commented on wbooks-api/Gemfile
> +  gem 'rubocop'
Always lock version: `gem 'rubocop', '~> 0.66.0'`

2019-03-27 14:03 UTC, facucompe approved these changes

2019-03-27 14:07 UTC, merged