Book model implementation
wolox-training/megl-rails pull request #5
Opened 2019-03-28 13:48 UTC by marcegl91

### Summary

- Added book model and initial files for rspec.

### Trello Card

https://trello.com/c/7D4o6LxB/18-crear-modelo-de-book

2019-03-28 21:18 UTC, facucompe requested changes

2019-03-28 21:18 UTC, facucompe commented on wbooks-api/app/models/book.rb
> +class Book < ApplicationRecord
Add presence validation for required fields

2019-03-29 20:06 UTC, facucompe approved these changes

2019-04-03 13:16 UTC, floresv approved these changes
LGTM

2019-04-03 13:18 UTC, merged