Book model testing
wolox-training/megl-rails pull request #6
Opened 2019-03-28 14:15 UTC by marcegl91

### Summary

- Added tests for book model and configuration code for Faker, FactoryBot, DatabaseCleaner and Shoulda-Matchers.

### Trello Card

https://trello.com/c/AAdzmSX5/20-crear-tests-para-el-modelo-de-book

2019-03-28 21:28 UTC, facucompe requested changes

2019-03-28 21:28 UTC, facucompe commented on wbooks-api/spec/factories/book.rb
> +      genre { 'Dystopian' }
Use faker for all this fields

2019-03-28 21:28 UTC, facucompe commented on wbooks-api/spec/factories/book.rb
> +      genre { 'Dystopian' }
`Faker::Book.genre` for example

2019-03-28 21:28 UTC, facucompe commented on wbooks-api/app/models/book.rb
> +  validates :genre, :author, :image, :title, :editor, :year, presence: true
Ah, you did it here, ok

2019-03-28 21:28 UTC, facucompe commented on wbooks-api/spec/factories/book.rb
> +    factory :valid_book do
Instead of doing this i prefer using traits or setting a field value in the test

2019-03-28 21:28 UTC, facucompe commented on wbooks-api/spec/models/book_spec.rb
> +    subject(:book) { build(:book) }
Here instead of doing this i would prefer: 
```
subject(:book) { build(:book, title: nil) }
```

2019-03-29 20:12 UTC, facucompe approved these changes

2019-04-03 13:17 UTC, floresv approved these changes
LGTM

2019-04-03 13:26 UTC, merged