Book#index and Book#show implementation
wolox-training/megl-rails pull request #8
Opened 2019-03-29 16:36 UTC by marcegl91

### Summary

- Added Book#index and Book#show actions, also defined factories for user, rent and book and fixed naming in models to follow API requirements.

### Trello Card

https://trello.com/c/eKCgYnNv/21-crear-rutas-index-y-show-para-book

2019-03-29 20:38 UTC, facucompe approved these changes

2019-03-29 20:38 UTC, facucompe commented on wbooks-api/app/controllers/api/v1/books_controller.rb
> +        @books = Book.all
There is no need to use instance variables here

2019-03-29 20:38 UTC, facucompe commented on wbooks-api/app/controllers/api/v1/books_controller.rb
> +      before_action :authenticate_user!
We usually create an `ApiController` that is in charge or this. All the other controllers inheritates from this. You can keep it this way

2019-03-29 20:38 UTC, facucompe commented on wbooks-api/app/helpers/books_helper.rb
> +module BooksHelper
Remove this empty module

2019-03-29 20:38 UTC, facucompe commented on wbooks-api/app/models/image.rb
> +  has_one :book, dependent: :destroy
I would use `dependent: :nullify` instead

2019-03-29 20:38 UTC, facucompe commented on wbooks-api/config/routes.rb
> +      get '/books', to: 'books#index'
`  resources :books, only: [:show, :index]`

2019-03-29 20:41 UTC, facucompe requested changes
Sorry, i clicked the wrong  button

2019-04-02 12:49 UTC, facucompe submitted a review, later dismissed

2019-04-02 12:49 UTC, facucompe commented on wbooks-api/app/controllers/api/v1/books_controller.rb
> +        render_paginated books, each_serializer: BookIndexSerializer
you can do `render_paginated Book.all`

2019-04-02 12:49 UTC, facucompe commented on wbooks-api/app/controllers/api/v1/books_controller.rb
> +        render json: book, serializer: BookShowSerializer
`render json: Book.find(params[:id])`

2019-04-03 13:03 UTC, floresv commented on wbooks-api/app/controllers/api/v1/books_controller.rb
> +        render_paginated books, each_serializer: BookIndexSerializer
I agree

2019-04-03 13:04 UTC, floresv commented on wbooks-api/app/controllers/api/v1/books_controller.rb
> +        render json: book, serializer: BookShowSerializer
With facu rlz :metal:

2019-04-03 13:04 UTC, floresv commented on wbooks-api/app/models/rent.rb
> +    returned_at.blank?
Suspicious :thinking:

2019-04-03 13:06 UTC, floresv commented on wbooks-api/app/models/book.rb
> +    rents.find(&:active?)
I thinks It's better using a scope.. :thinking:

2019-04-05 12:53 UTC, facucompe approved these changes

2019-04-08 14:58 UTC, floresv approved these changes

2019-04-08 15:10 UTC, merged