Implemented tests for book#index and book#show
wolox-training/megl-rails pull request #9
Opened 2019-03-29 18:08 UTC by marcegl91

### Summary

- Implemented tests for book#index and book#show

### Trello Card

https://trello.com/c/KT3eY0kx/22-crear-tests-para-rutas-index-y-show-de-book

2019-03-29 20:49 UTC, facucompe requested changes
Just that small change

2019-03-29 20:49 UTC, facucompe commented on wbooks-api/spec/controllers/api/v1/books_controller_spec.rb
> +        content = JSON.parse(response.body)['page']
we always define a helper to do this. Add this:
```
module Response
  module JSONParser
    def response_body
      ActiveSupport::JSON.decode(response.body) if response.present?
    end
  end
end
```
in `spec/support/parsed_response_helper.rb` . Also add it in `rails_helper`

2019-04-02 12:49 UTC, facucompe approved these changes

2019-04-03 13:20 UTC, floresv requested changes
and failure cases?

2019-04-05 12:55 UTC, facucompe approved these changes

2019-04-08 14:59 UTC, floresv approved these changes
LGTM

2019-04-08 15:17 UTC, merged